import type { Channel, Product, Series } from "./types";

export const defaultChannels: Channel[] = [
  { id: "ch-jd", name: "京东", code: "jd", sortOrder: 1 },
  { id: "ch-tmall", name: "天猫", code: "tmall", sortOrder: 2 },
  { id: "ch-pdd", name: "拼多多", code: "pdd", sortOrder: 3 },
  { id: "ch-douyin", name: "抖音", code: "douyin", sortOrder: 4 },
  { id: "ch-meituan", name: "美团", code: "meituan", sortOrder: 5 },
];

const now = new Date().toISOString();

export const defaultSeries: Series[] = [
  {
    id: "ser-heijin",
    name: "黑金系列",
    slug: "hei-jin",
    description: "志金旗舰 · 团购渠道主力，老藤混酿高端礼赠",
    channelLabel: "团购渠道",
    image: "",
    published: true,
    sortOrder: 1,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ser-dag",
    name: "大G系列",
    slug: "da-g-xi-lie",
    description: "电商走量爆款，高性价比干红",
    channelLabel: "电商渠道",
    image: "",
    published: true,
    sortOrder: 2,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ser-gnum",
    name: "G数字系列",
    slug: "g-shu-zi",
    description: "G300/G500/G800 等数字产品线，覆盖多价格带",
    channelLabel: "电商/自营",
    image: "",
    published: true,
    sortOrder: 3,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ser-jijin",
    name: "基金系列",
    slug: "ji-jin",
    description: "干白与特色品类",
    channelLabel: "电商渠道",
    image: "",
    published: true,
    sortOrder: 4,
    createdAt: now,
    updatedAt: now,
  },
];

function sku(
  id: string,
  name: string,
  salesSpec: string,
  sortOrder: number,
  jd: number,
  tmall: number,
  pdd: number,
  douyin: number,
  meituan?: number,
) {
  return {
    id,
    name,
    salesSpec,
    sortOrder,
    prices: [
      { channelId: "ch-jd", price: jd },
      { channelId: "ch-tmall", price: tmall },
      { channelId: "ch-pdd", price: pdd },
      { channelId: "ch-douyin", price: douyin },
      { channelId: "ch-meituan", price: meituan ?? jd },
    ],
  };
}

export const defaultProducts: Product[] = [
  {
    id: "prod-dajin",
    name: "大金锤",
    slug: "da-jin-chui",
    seriesId: "ser-heijin",
    positioning: "团购渠道",
    category: "干红",
    varietal: "西拉子/赤霞珠",
    wineStyle: "果香型",
    bottleType: "重型瓶",
    gwa: "白金奖/金奖 99/98",
    region: "南澳/百茨谷内湾",
    vineAge: "40年+",
    oakGrade: "A+",
    oakAging: "12-14个月",
    alcohol: "15.3%",
    description:
      "黑金系列旗舰款，选用40年以上老藤西拉子与赤霞珠混酿，经A+级橡木桶陈酿12-14个月，酒体饱满、层次丰富。",
    image: "",
    priceSegment: "mid-high",
    featured: true,
    published: true,
    sortOrder: 1,
    skus: [
      sku("sku-dajin-1", "单支礼盒/1瓶装", "750ml×1 牛皮纸袋", 1, 399, 399, 399, 369),
      sku("sku-dajin-2", "双支礼盒/2瓶装", "750ml×2 红色礼盒", 2, 798, 798, 798, 738),
      sku("sku-dajin-6", "整箱/6瓶装", "750ml×6 整箱", 3, 2388, 2388, 2388, 2158),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-xiaojin",
    name: "小金锤",
    slug: "xiao-jin-chui",
    seriesId: "ser-heijin",
    positioning: "团购渠道",
    category: "干红",
    varietal: "西拉子/赤霞珠",
    wineStyle: "果香型",
    bottleType: "重型瓶",
    gwa: "金奖 98",
    region: "南澳",
    vineAge: "30年+",
    oakGrade: "A",
    oakAging: "10-12个月",
    alcohol: "14.8%",
    description: "黑金系列经典款，30年以上葡萄藤酿造，口感圆润平衡。",
    image: "",
    priceSegment: "mid",
    featured: true,
    published: true,
    sortOrder: 2,
    skus: [
      sku("sku-xiaojin-1", "单支礼盒/1瓶装", "750ml×1", 1, 199, 199, 189, 179),
      sku("sku-xiaojin-2", "双支礼盒/2瓶装", "750ml×2 礼盒", 2, 398, 398, 378, 358),
      sku("sku-xiaojin-6", "整箱/6瓶装", "750ml×6", 3, 1099, 1099, 999, 949),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-ganbai",
    name: "金锤干白",
    slug: "jin-chui-gan-bai",
    seriesId: "ser-jijin",
    positioning: "电商渠道",
    category: "干白",
    varietal: "霞多丽",
    wineStyle: "青调型",
    bottleType: "勃艮第瓶",
    gwa: "金奖 96",
    region: "南澳",
    vineAge: "25年+",
    oakGrade: "A",
    oakAging: "6-8个月",
    alcohol: "13.5%",
    description: "基金系列干白，霞多丽酿造，清新果香与矿物感平衡。",
    image: "",
    priceSegment: "mid",
    featured: true,
    published: true,
    sortOrder: 3,
    skus: [
      sku("sku-ganbai-1", "单支礼盒/1瓶装", "750ml×1", 1, 219, 219, 199, 179),
      sku("sku-ganbai-2", "双支礼盒/2瓶装", "750ml×2", 2, 438, 438, 398, 358),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-dag",
    name: "大G",
    slug: "da-g",
    seriesId: "ser-dag",
    positioning: "电商渠道",
    category: "干红",
    varietal: "西拉",
    wineStyle: "果香型",
    bottleType: "普通瓶",
    gwa: "银奖 91",
    region: "南澳",
    vineAge: "20年+",
    oakGrade: "B",
    oakAging: "6个月",
    alcohol: "14.5%",
    description: "大G系列入门爆款，高性价比干红，适合电商走量。",
    image: "",
    priceSegment: "entry",
    featured: false,
    published: true,
    sortOrder: 4,
    skus: [
      sku("sku-dag-1", "单支/1瓶装", "750ml×1", 1, 48, 49, 49, 49),
      sku("sku-dag-2", "双支/2瓶装", "750ml×2", 2, 99, 99, 99, 99),
      sku("sku-dag-6", "整箱/6瓶装", "750ml×6", 3, 199, 199, 199, 159),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-g300",
    name: "G300",
    slug: "g300",
    seriesId: "ser-gnum",
    positioning: "电商渠道",
    category: "干红",
    varietal: "赤霞珠",
    wineStyle: "果香型",
    bottleType: "普通瓶",
    gwa: "银奖 92",
    region: "南澳",
    vineAge: "20年+",
    oakGrade: "B",
    oakAging: "6个月",
    alcohol: "14.0%",
    description: "G数字系列中端款，赤霞珠单酿，结构清晰、易饮。",
    image: "",
    priceSegment: "entry",
    featured: false,
    published: true,
    sortOrder: 5,
    skus: [
      sku("sku-g300-1", "单支/1瓶装", "750ml×1", 1, 70, 89, 79, 79),
      sku("sku-g300-6", "整箱/6瓶装", "750ml×6", 2, 399, 499, 449, 429),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-g500",
    name: "G500",
    slug: "g500",
    seriesId: "ser-gnum",
    positioning: "京东自营",
    category: "干红",
    varietal: "西拉/赤霞珠",
    wineStyle: "果香型",
    bottleType: "普通瓶",
    gwa: "银奖 93",
    region: "南澳",
    vineAge: "25年+",
    oakGrade: "B",
    oakAging: "8个月",
    alcohol: "14.2%",
    description: "G500 混酿干红，京东自营渠道专供规格。",
    image: "",
    priceSegment: "mid",
    featured: false,
    published: true,
    sortOrder: 6,
    skus: [
      sku("sku-g500-1", "单支礼盒/1瓶装", "750ml×1", 1, 129, 129, 119, 119),
      sku("sku-g500-2", "双支礼盒/2瓶装", "750ml×2", 2, 258, 258, 238, 228),
    ],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod-g800",
    name: "G800",
    slug: "g800",
    seriesId: "ser-gnum",
    positioning: "即将上市",
    category: "干红",
    varietal: "西拉",
    wineStyle: "浓郁型",
    bottleType: "重型瓶",
    gwa: "待评",
    region: "南澳",
    vineAge: "30年+",
    oakGrade: "A",
    oakAging: "10个月",
    alcohol: "14.8%",
    description: "G800 高端款，即将上市，可提前向渠道伙伴预告。",
    image: "",
    priceSegment: "mid-high",
    featured: false,
    published: true,
    sortOrder: 7,
    skus: [
      sku("sku-g800-1", "单支礼盒/1瓶装", "750ml×1", 1, 389, 399, 189, 189),
    ],
    createdAt: now,
    updatedAt: now,
  },
];
